### PR TITLE
Allow Forecasts to be pickled and unpickled safely

### PR DESCRIPTION
**Pull request by shakefu**
- Updates `Forecast.__getattr__` to use `__getattribute__` instead of dot-notation attribute access, which relies on instance attributes already having been created in `__init__`.
- Fixes unpickling of `Forecast` instances breaking due to infinite recursion in `__getattr__`.
- Creates a regression test for the fix, and a basic test suite, without adding any package dependencies (run tests via `python setup.py test`).
- Adds a test fixture for an example Dark Sky API response, so we don't have to have a working API key to run tests.

### CODE REVIEW

**Comment by lukaskubis** [comment]
@shakefu nice job on the `__getattribute__`. I'm just a little confused as to what the pickling/unpickling issue was?

**Comment by shakefu** [comment]
@lukaskubis - When unpickling, the *pickle* library makes some direct calls to `__getattr__` as part of its memoization. Those calls are made before the class instance `__dict__` is instantiated, so when it is unpickling it would call `__getattr__` which internally tried to access `self.currently` - because the class instance did not have a `currently` attribute yet, that attribute access would in turn call `__getattr__(self, 'currently')` which created an infinite recursion, preventing the unpickling from succeeding.

**Comment by shakefu** [comment]
Any word on getting this merged and published as a new release @lukaskubis?

**Comment by lukaskubis** [comment]
@shakefu yes, just need some time to set up CI (might as well). I'll merge it by the end of the week.

*Edit:* Well, that did not happen...

**Comment by AggressivelyMeows** [comment]
Any chance of this being merged soon? Being able to pickle and save the results for later is very useful

**Pull request merged**
